services:

  # The forum
  n_flarum:
    image: jeromegillard/flarum:latest
    env_file:
      - ${CLUSTER_HOME}/flarum/.env
      - ${CLUSTER_HOME}/flarum/.env.local
    volumes:
      - ${CLUSTER_HOME}/flarum/assets:/flarum/app/public/assets
      - ${CLUSTER_HOME}/flarum/extensions:/flarum/app/extensions
      - ${CLUSTER_HOME}/flarum/nginx:/etc/nginx/flarum
      - ${CLUSTER_HOME}/flarum/vendor:/flarum/app/vendor    
    depends_on:
      - n_db
    networks:
      - nonceveux_be
      - cluster_net # external bridge

  # The database
  n_db:
    image: linuxserver/mariadb
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/data:/var/lib/mysql
    networks:
      - nonceveux_be
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.hn == p6'

  # The DB backup
  mariadb-backup:
    build: .
    restart: unless-stopped
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    networks:
      - cluster_net


  # An optional DB interface
  n_phpmyadmin:
    image: phpmyadmin
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    depends_on:
      - n_db
    networks:
      - nonceveux_be
      - cluster_net # external bridge

  n_nginx:
    image: nginx
    volumes:
      - ${CLUSTER_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CLUSTER_HOME}/nginx/conf.d/nonceveux.be.conf:/etc/nginx/conf.d/nonceveux.be.conf:ro
      - ${CLUSTER_HOME}/nginx/html:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nonceveux_be
      - cluster_net # external bridge

networks:
  # The stack network
  nonceveux_be:
    name: nonceveux_be

  # This stack is not directly exposed. Bridge it to another one.
  cluster_net:
    name: h3_cluster_net
    external: true