version: "3.9"

services:
  # The reverse proxy  
  n_traefik:
    image: traefik
    restart: always
    env_file: 
      - ${CLUSTER_HOME}/traefik/.env
      - ${CLUSTER_HOME}/traefik/.env.local
    volumes:
      - ${CLUSTER_HOME}/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${CLUSTER_HOME}/traefik/letsencrypt:/letsencrypt
      - ${CLUSTER_HOME}/traefik/conf:/conf
      - /etc/localtime:/etc/localtime
    ports:
      - 1580:80       # HTTP, custom external ports because already behind another Treafik instance.
      - 15443:443     # TLS
    networks:
      - nonceveux_be
      - cluster_net # external 


  # The forum
  n_flarum:
    image: mondedie/flarum:stable
    container_name: n_flarum
    restart: always
    env_file:
      - ${CLUSTER_HOME}/flarum/.env
      - ${CLUSTER_HOME}/flarum/.env.local
    volumes:
      - ${CLUSTER_HOME}/flarum/assets:/flarum/app/public/assets
      - ${CLUSTER_HOME}/flarum/extensions:/flarum/app/extensions
      - ${CLUSTER_HOME}/flarum/nginx:/etc/nginx/flarum
      - ${CLUSTER_HOME}/flarum/vendor:/flarum/app/vendor    
    depends_on:
      - n_db
    networks:
      - nonceveux_be

  # The database
  n_db:
    image: mariadb:10.5
    container_name: n_db
    restart: always
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/data:/var/lib/mysql
    networks:
      - nonceveux_be

  # The DB backup
  n_db-backup:
    image: mariadb:10.5
    container_name: n_db-backup
    restart: always
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h n_db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        ls -tr /dump/dump_*.sql.gz | head -n -"$$BACKUP_NUM_KEEP" | xargs -r rm
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    depends_on:
      - n_db
    networks:
      - nonceveux_be

  # An optional DB interface
  n_phpmyadmin:
    image: phpmyadmin
    container_name: n_phpmyadmin
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    restart: unless-stopped
    depends_on:
      - n_db
    networks:
      - nonceveux_be

  n_nginx:
    image: nginx
    restart: always
    container_name: n_nginx
    volumes:
      - ${CLUSTER_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CLUSTER_HOME}/nginx/conf.d/nonceveux.be.conf:/etc/nginx/conf.d/nonceveux.be.conf:ro
      - ${CLUSTER_HOME}/nginx/html:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nonceveux_be

networks:
  # The stack network
  nonceveux_be:
    name: nonceveux_be

  # This stack is not directly exposed. Bridge it to another one.
  cluster_net:
    name: cluster_cluster_net
    external: true