
services:

  # The forum
  flarum:
    image: jeromegillard/flarum:latest
    env_file:
      - ${CLUSTER_HOME}/flarum/.env
      - ${CLUSTER_HOME}/flarum/.env.local
    volumes:
      - flarum-app:/flarum/app
      - ${CLUSTER_HOME}/flarum/nginx:/etc/nginx/flarum
    depends_on:
      - db
    networks:
      - nonceveux_be
      - cluster_net # external bridge

  # The database
  db:
    image: linuxserver/mariadb
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/data:/var/lib/mysql
    networks:
      - nonceveux_be
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.hn == K5'

  # The DB backup
  db_backup:
    image: jeromegillard/mariadb-backup
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - nonceveux_be


  # An optional DB interface
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    depends_on:
      - db
    networks:
      - nonceveux_be
      - cluster_net # external bridge

  nginx:
    image: nginx
    volumes:
      - ${CLUSTER_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CLUSTER_HOME}/nginx/conf.d/nonceveux.be.conf:/etc/nginx/conf.d/nonceveux.be.conf:ro
      - ${CLUSTER_HOME}/nginx/html:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nonceveux_be
      - cluster_net # external bridge
  
  ghost:
    image: ghost 
    env_file:
      - ${CLUSTER_HOME}/ghost/.env
      - ${CLUSTER_HOME}/ghost/.env.local
    volumes:
      - ghost-data:/var/lib/ghost/current/content      
      - ${CLUSTER_HOME}/ghost/themes/casper:/var/lib/ghost/current/content/themes/casper
      - ${CLUSTER_HOME}/ghost/config.production.json:/var/lib/ghost/config.production.json
    networks:
      - nonceveux_be
      - cluster_net

networks:
  # The stack network
  nonceveux_be:
    name: nonceveux_be

  # This stack is not directly exposed. Bridge it to another one.
  cluster_net:
    name: h3_cluster_net
    external: true

volumes:

  
  flarum-app:
    driver: "vieux/sshfs:next"
    driver_opts:
      sshcmd: "${N_VOL_SSHCMD}/flarum"
      password: ${N_SSHFS_PASS}
      allow_other: ""

  ghost-data:
    driver: "vieux/sshfs:next"
    driver_opts:
      sshcmd: "${N_VOL_SSHCMD}/ghost/data"
      password: ${N_SSHFS_PASS}
      allow_other: ""