
services:

  # The forum
  flarum:
    image: jeromegillard/flarum:latest
    env_file:
      - ${CLUSTER_HOME}/flarum/.env
      - ${CLUSTER_HOME}/flarum/.env.local
    volumes:
      - ${CLUSTER_HOME}/flarum/assets:/flarum/app/public/assets
      - ${CLUSTER_HOME}flarum/extensions:/flarum/app/extensions
      - ${CLUSTER_HOME}flarum/vendor:/flarum/app/vendor
      - ${CLUSTER_HOME}/flarum/nginx:/etc/nginx/flarum
    depends_on:
      - db
    networks:
      - nonceveux_be
      - cluster_net # external bridge
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==c1.h3.network

  # The database
  db:
    image: mariadb:10.5
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/data:/var/lib/mysql
    networks:
      - nonceveux_be
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==c1.h3.network

  # The DB backup
  db_backup:
    image: jeromegillard/mariadb-backup
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    volumes:
      - ${CLUSTER_HOME}/mariadb/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - nonceveux_be
    deploy:
        replicas: 1
        placement:
          constraints:
            - node.hostname==c1.h3.network
      


  # An optional DB interface
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - ${CLUSTER_HOME}/mariadb/.env
      - ${CLUSTER_HOME}/mariadb/.env.local
    depends_on:
      - db
    networks:
      - nonceveux_be
      - cluster_net # external bridge
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname==c1.h3.network

  nginx:
    image: nginx
    volumes:
      - ${CLUSTER_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CLUSTER_HOME}/nginx/conf.d/nonceveux.be.conf:/etc/nginx/conf.d/nonceveux.be.conf:ro
      - ${CLUSTER_HOME}/nginx/html:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nonceveux_be
      - cluster_net # external bridge
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==c1.h3.network
  
  ghost:
    image: ghost 
    env_file:
      - ${CLUSTER_HOME}/ghost/.env
      - ${CLUSTER_HOME}/ghost/.env.local
    volumes:
      - ${CLUSTER_HOME}/data:/var/lib/ghost/content 
      - ${CLUSTER_HOME}/ghost/themes/casper:/var/lib/ghost/content/themes/casper
      - ${CLUSTER_HOME}/ghost/config.production.json:/var/lib/ghost/config.production.json
    networks:
      - nonceveux_be
      - cluster_net
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname==c1.h3.network

  ecole_ghost:
    image: ghost 
    env_file:
      - ${CLUSTER_HOME}/ecole/.env
      - ${CLUSTER_HOME}/ecole/.env.local
    volumes:
      - ${CLUSTER_HOME}/ecole:/var/lib/ghost/content 
      - ${CLUSTER_HOME}/ecole/config.production.json:/var/lib/ghost/config.production.json
    networks:
      - nonceveux_be
      - cluster_net
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.hostname==c1.h3.network

networks:
  # The stack network
  nonceveux_be:
    name: nonceveux_be

  # This stack is not directly exposed. Bridge it to another one.
  cluster_net:
    name: h3_cluster_net
    external: true